--
-- PostgreSQL database dump
--

\restrict wcJDNB8ZJZKWOAmm88HkSxtchOuYfgIdYpoVrZ1PXBmbxyiWlBnCmGxNsKE3K47

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assets_asset; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.assets_asset (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    barcode_id character varying(100),
    serial_number character varying(100) NOT NULL,
    purchase_date date,
    price numeric(15,0),
    status character varying(20) NOT NULL,
    note text,
    "current_user" character varying(100),
    current_dept character varying(100),
    prev_user character varying(100),
    prev_dept character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    kategori_id bigint,
    lokasi_id bigint
);


ALTER TABLE public.assets_asset OWNER TO mahsaserver;

--
-- Name: assets_asset_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.assets_asset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_asset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_assethistory; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.assets_assethistory (
    id bigint NOT NULL,
    event_date timestamp with time zone NOT NULL,
    description text NOT NULL,
    asset_id bigint NOT NULL,
    changed_by_id integer
);


ALTER TABLE public.assets_assethistory OWNER TO mahsaserver;

--
-- Name: assets_assethistory_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.assets_assethistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_assethistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_kategori; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.assets_kategori (
    id bigint NOT NULL,
    nama character varying(100) NOT NULL
);


ALTER TABLE public.assets_kategori OWNER TO mahsaserver;

--
-- Name: assets_kategori_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.assets_kategori ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_kategori_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assets_lokasi; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.assets_lokasi (
    id bigint NOT NULL,
    nama character varying(100) NOT NULL
);


ALTER TABLE public.assets_lokasi OWNER TO mahsaserver;

--
-- Name: assets_lokasi_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.assets_lokasi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_lokasi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO mahsaserver;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO mahsaserver;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO mahsaserver;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO mahsaserver;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO mahsaserver;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO mahsaserver;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO mahsaserver;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO mahsaserver;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO mahsaserver;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: mahsaserver
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: mahsaserver
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO mahsaserver;

--
-- Data for Name: assets_asset; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.assets_asset (id, name, barcode_id, serial_number, purchase_date, price, status, note, "current_user", current_dept, prev_user, prev_dept, created_at, updated_at, kategori_id, lokasi_id) FROM stdin;
2	asus rog	04250006	3232318531	2025-12-12	\N	DIPAKAI		budi	hrd	\N	\N	2026-02-04 10:25:00.22165+00	2026-02-04 10:25:00.22166+00	1	1
3	Dell Latitude 3420	04240009	DPSJGX3	\N	8991000	DIPAKAI	\N	Sayusen Hasanah	Sales	\N	\N	2026-02-22 03:56:55.827994+00	2026-02-22 03:56:55.828008+00	1	2
4	Asus Vivobook E1404F	04240010	S1N0CV00B27701C	\N	8214000	DIPAKAI	\N	Urip Banuroso Ex Martin Dwinanto	Product & Development	\N	\N	2026-02-22 03:56:55.831929+00	2026-02-22 03:56:55.831962+00	1	3
5	Dell Inspiron 7430	04240012	FNLXYW3	\N	12500000	DIPAKAI	\N	Rahman Darma Rahadian	Sales	\N	\N	2026-02-22 03:56:55.834469+00	2026-02-22 03:56:55.834477+00	1	3
6	HP DQ5115TU	04240013	5CD34971B6	\N	7104000	DIPAKAI	\N	Roni Franki Hasudungan	Sales	\N	\N	2026-02-22 03:56:55.83759+00	2026-02-22 03:56:55.837597+00	1	4
8	HP DQ5115TU	04250002	5CD3497OXJ	\N	6882000	DIPAKAI	\N	Patricia Lauren	Marketing	\N	\N	2026-02-22 03:56:55.843229+00	2026-02-22 03:56:55.843236+00	1	3
9	HP Pavilion - 14-bf194tx	24180008	CND8105R40	\N	0	DIPAKAI	\N	Ellen Marcella	AR	\N	\N	2026-02-22 03:56:55.845772+00	2026-02-22 03:56:55.84578+00	1	5
10	HP Envy x360 14-fc0555TU	04250003	CND4363740	\N	17209440	DIPAKAI	\N	Arleen Amidjaja	BOD	\N	\N	2026-02-22 03:56:55.848922+00	2026-02-22 03:56:55.84893+00	1	6
11	Dell Latitude 3420	04250004	GW8ZLS3	\N	7903200	TERSEDIA	\N	Dilemari IT 34	IT	\N	\N	2026-02-22 03:56:55.852122+00	2026-02-22 03:56:55.852129+00	1	7
12	Dell Latitude 3420	04250005	2P7ZLS3	\N	7903200	DIPAKAI	\N	Adi Rukmantara	Sales	\N	\N	2026-02-22 03:56:55.855089+00	2026-02-22 03:56:55.855096+00	1	8
13	Dell Latitude 3420	04250007	537ZLS3	\N	7903200	DIPAKAI	\N	Mogi Peksiprakasa	Sales	\N	\N	2026-02-22 03:56:55.857342+00	2026-02-22 03:56:55.857349+00	1	3
14	Dell Latitude 3420	04250006	26CZLS3	\N	7903200	DIPAKAI	\N	Dennison Enrico Pryana	Sales	\N	\N	2026-02-22 03:56:55.859618+00	2026-02-22 03:56:55.859625+00	1	3
15	Dell Inspiron 14 7440	04250008	CK52K24	\N	10450000	DIPAKAI	\N	Yohanes Sugianto	FAT	\N	\N	2026-02-22 03:56:55.861876+00	2026-02-22 03:56:55.861883+00	1	5
16	Acer Aspire Lite AL14-32P-C9VS	04250009	NXD3KSN00250900B516L01	\N	5550000	DIPAKAI	\N	Annisa Khairani	Marketing	\N	\N	2026-02-22 03:56:55.864774+00	2026-02-22 03:56:55.864781+00	1	9
17	Acer Aspire Lite AL14-32P-C9VS	04250010	NXD3KSN002509005B36L01	\N	5550000	DIPAKAI	\N	John Junior Allain Hendrik	Sales	\N	\N	2026-02-22 03:56:55.867023+00	2026-02-22 03:56:55.867031+00	1	2
18	Asus A41404VA-VIPS5510	04250011	S6N0CX10P617262	\N	8824500	DIPAKAI	\N	Faizal Maulidhany Rarin	Sales	\N	\N	2026-02-22 03:56:55.869867+00	2026-02-22 03:56:55.869875+00	1	10
19	HP 14-ep1063cl	04250012	1H9439085V	\N	5589000	DIPAKAI	\N	Fransiscus Deni	Trade	\N	\N	2026-02-22 03:56:55.872101+00	2026-02-22 03:56:55.872108+00	1	3
20	Acer Aspire Lite AL14-32P-C9VS	04250013	NXD3SLN00252103B976L01	\N	5550000	DIPAKAI	\N	Riza Fridianawati	Sales	\N	\N	2026-02-22 03:56:55.874326+00	2026-02-22 03:56:55.874333+00	1	8
21	Asus A41404VA-VIPS5510	04250014	T1NOCX02F849027	\N	6987450	DIPAKAI	\N	Eko Winanto	Sales	\N	\N	2026-02-22 03:56:55.876512+00	2026-02-22 03:56:55.876518+00	1	4
22	Acer Aspire Lite AL14-32P-C9VS	04250015	NXD3KSN002507002146L01	\N	5550000	DIPAKAI	\N	Muhammad Apriansyah	Sales	\N	\N	2026-02-22 03:56:55.878705+00	2026-02-22 03:56:55.878712+00	1	8
23	Acer Aspire Lite AL14-32P-C9VS	04250016	NXD3KSN00252101D16L01	\N	5550000	DIPAKAI	\N	Eko Sigit Prabowo	Sales	\N	\N	2026-02-22 03:56:55.880907+00	2026-02-22 03:56:55.880914+00	1	8
24	Acer Aspire Lite AL14-32P-C9VS	04250017	NXD4NSN0025150314E6L01	\N	5550000	DIPAKAI	\N	Natanael Deska Prahatma	Internal Control	\N	\N	2026-02-22 03:56:55.883148+00	2026-02-22 03:56:55.883155+00	1	5
25	MSI Thin 15 B12UC-2411ID	04250018	K2501N0091205	\N	9407250	DIPAKAI	\N	Robby Maulana Turnip	Information System	\N	\N	2026-02-22 03:56:55.885343+00	2026-02-22 03:56:55.88535+00	1	7
26	Lenovo V14 G4	04250019	PF5A0SM2	\N	6088350	DIPAKAI	\N	Edy Susanto	Sales	\N	\N	2026-02-22 03:56:55.887512+00	2026-02-22 03:56:55.887519+00	1	2
27	Redmi 12C	13230003	46048/13WQ00228	\N	0	DIPAKAI	\N	Safira Hasanah	Marketing	\N	\N	2026-02-22 03:56:55.890563+00	2026-02-22 03:56:55.89057+00	2	1
28	Redmi 12C	13230004	46048/13TR05847	\N	0	DIPAKAI	\N	Safira Hasanah	Marketing	\N	\N	2026-02-22 03:56:55.892807+00	2026-02-22 03:56:55.892815+00	2	1
29	Redmi 12C	13230005	46048/13WQ00263	\N	0	DIPAKAI	\N	Wanda Megawati	Marketing	\N	\N	2026-02-22 03:56:55.895073+00	2026-02-22 03:56:55.89508+00	2	1
30	Poco M6	99240004	5759214SZ11106	\N	0	DIPAKAI	\N	Anissa Khomsatun	Marketing	\N	\N	2026-02-22 03:56:55.897303+00	2026-02-22 03:56:55.89731+00	2	3
31	Itel Vista Tab 30	13250002	358826230196301	\N	0	DIPAKAI	\N	Bengkel Prima Motor	Marketing	\N	\N	2026-02-22 03:56:55.900401+00	2026-02-22 03:56:55.900408+00	3	4
32	Itel Vista Tab 30	13250003	358826230198828	\N	0	DIPAKAI	\N	Bengkel Ratu Agung	Marketing	\N	\N	2026-02-22 03:56:55.902669+00	2026-02-22 03:56:55.902677+00	3	4
33	Itel Vista Tab 30	13250004	358826230203685	\N	0	TERSEDIA	\N	Lemari IT 34	Information System	\N	\N	2026-02-22 03:56:55.904885+00	2026-02-22 03:56:55.904892+00	3	7
34	Itel Vista Tab 30	13250005	358826230203248	\N	0	TERSEDIA	\N	Lemari IT 34	Information System	\N	\N	2026-02-22 03:56:55.907145+00	2026-02-22 03:56:55.907153+00	3	7
35	Itel Vista Tab 30	13250006	358826230196442	\N	0	TERSEDIA	\N	Lemari IT 34	Information System	\N	\N	2026-02-22 03:56:55.909343+00	2026-02-22 03:56:55.90935+00	3	7
36	EPPOS Plus 80mm Thermal	08250004	2024110000	\N	0	TERSEDIA	\N	Lemari IT 34	Information System	\N	\N	2026-02-22 03:56:55.912221+00	2026-02-22 03:56:55.912228+00	4	7
37	EPPOS Plus 80mm Thermal	08250005	2024110000	\N	0	TERSEDIA	\N	Lemari IT 34	Information System	\N	\N	2026-02-22 03:56:55.914423+00	2026-02-22 03:56:55.91443+00	4	7
38	Itel Vista Tab 30	99250003	358826230046340	\N	0	DIPAKAI	\N	Team Dev & BS IT	Information System	\N	\N	2026-02-22 03:56:55.916655+00	2026-02-22 03:56:55.916663+00	3	7
39	EPPOS Plus 80mm Thermal	08250003	2024110000	\N	0	DIPAKAI	\N	Team Dev & BS IT	Information System	\N	\N	2026-02-22 03:56:55.918842+00	2026-02-22 03:56:55.918849+00	4	7
40	Samsung A06	13250007	352978/78/164861/4	\N	0	DIPAKAI	\N	Dhea Nirwana	Marketing	\N	\N	2026-02-22 03:56:55.921081+00	2026-02-22 03:56:55.921088+00	2	1
41	Samsung A07	13250008	R9RY801PYPOE	\N	0	RUSAK	\N	Citra Paramitha	General Affair	\N	\N	2026-02-22 03:56:55.923298+00	2026-02-22 03:56:55.923305+00	2	1
42	Samsung A07	13250009	R9RY8038M0K	\N	0	RUSAK	\N	Mahsa Almira	General Affair	\N	\N	2026-02-22 03:56:55.925503+00	2026-02-22 03:56:55.92551+00	2	1
43	Samsung A07	13250010	R9RY801P7XY	\N	0	RUSAK	\N	Debby Angelina	HRD	\N	\N	2026-02-22 03:56:55.927718+00	2026-02-22 03:56:55.927728+00	2	1
44	Redmi 14C	13250011	58703/14w722193	\N	0	DIPAKAI	\N	Hamdan Ilham	Information System	\N	\N	2026-02-22 03:56:55.930006+00	2026-02-22 03:56:55.930014+00	2	7
45	Redmi 12C	13230001	46048/13RE03513	\N	0	DIPAKAI	\N	Muhammad Ridhwan	Information System	\N	\N	2026-02-22 03:56:55.932232+00	2026-02-22 03:56:55.932239+00	2	7
47	EPPOS Plus 80mm Thermal	08250002	2024110000	\N	0	DIPAKAI	\N	Bengkel Prima Motor	Marketing	\N	\N	2026-02-22 03:56:55.93715+00	2026-02-22 03:56:55.937158+00	4	4
46	EPPOS Plus 80mm Thermal	08250001	2024110000	\N	5000000	DIPAKAI		Bengkel Ratu Agung	Marketing	\N	\N	2026-02-22 03:56:55.934659+00	2026-02-22 03:57:35.730843+00	4	4
7	HP DQ5115TU	04250001	5CD34970Y7	\N	6882000	DIPAKAI		Jonathan	trade	Thomas Ali Sanjaya	Purchasing	2026-02-22 03:56:55.840756+00	2026-02-22 03:58:01.894877+00	1	5
\.


--
-- Data for Name: assets_assethistory; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.assets_assethistory (id, event_date, description, asset_id, changed_by_id) FROM stdin;
2	2026-02-04 10:25:00.222439+00	Aset baru didaftarkan ke sistem.	2	1
3	2026-02-22 03:56:55.828846+00	Aset ditambahkan massal via Import Excel.	3	1
4	2026-02-22 03:56:55.832434+00	Aset ditambahkan massal via Import Excel.	4	1
5	2026-02-22 03:56:55.834927+00	Aset ditambahkan massal via Import Excel.	5	1
6	2026-02-22 03:56:55.838065+00	Aset ditambahkan massal via Import Excel.	6	1
7	2026-02-22 03:56:55.841244+00	Aset ditambahkan massal via Import Excel.	7	1
8	2026-02-22 03:56:55.843675+00	Aset ditambahkan massal via Import Excel.	8	1
9	2026-02-22 03:56:55.846226+00	Aset ditambahkan massal via Import Excel.	9	1
10	2026-02-22 03:56:55.849389+00	Aset ditambahkan massal via Import Excel.	10	1
11	2026-02-22 03:56:55.852556+00	Aset ditambahkan massal via Import Excel.	11	1
12	2026-02-22 03:56:55.855512+00	Aset ditambahkan massal via Import Excel.	12	1
13	2026-02-22 03:56:55.85777+00	Aset ditambahkan massal via Import Excel.	13	1
14	2026-02-22 03:56:55.860068+00	Aset ditambahkan massal via Import Excel.	14	1
15	2026-02-22 03:56:55.862325+00	Aset ditambahkan massal via Import Excel.	15	1
16	2026-02-22 03:56:55.865218+00	Aset ditambahkan massal via Import Excel.	16	1
17	2026-02-22 03:56:55.867441+00	Aset ditambahkan massal via Import Excel.	17	1
18	2026-02-22 03:56:55.870308+00	Aset ditambahkan massal via Import Excel.	18	1
19	2026-02-22 03:56:55.872522+00	Aset ditambahkan massal via Import Excel.	19	1
20	2026-02-22 03:56:55.874748+00	Aset ditambahkan massal via Import Excel.	20	1
21	2026-02-22 03:56:55.876962+00	Aset ditambahkan massal via Import Excel.	21	1
22	2026-02-22 03:56:55.87917+00	Aset ditambahkan massal via Import Excel.	22	1
23	2026-02-22 03:56:55.881346+00	Aset ditambahkan massal via Import Excel.	23	1
24	2026-02-22 03:56:55.883569+00	Aset ditambahkan massal via Import Excel.	24	1
25	2026-02-22 03:56:55.885761+00	Aset ditambahkan massal via Import Excel.	25	1
26	2026-02-22 03:56:55.887927+00	Aset ditambahkan massal via Import Excel.	26	1
27	2026-02-22 03:56:55.891008+00	Aset ditambahkan massal via Import Excel.	27	1
28	2026-02-22 03:56:55.893253+00	Aset ditambahkan massal via Import Excel.	28	1
29	2026-02-22 03:56:55.8955+00	Aset ditambahkan massal via Import Excel.	29	1
30	2026-02-22 03:56:55.897722+00	Aset ditambahkan massal via Import Excel.	30	1
31	2026-02-22 03:56:55.900843+00	Aset ditambahkan massal via Import Excel.	31	1
32	2026-02-22 03:56:55.903123+00	Aset ditambahkan massal via Import Excel.	32	1
33	2026-02-22 03:56:55.905335+00	Aset ditambahkan massal via Import Excel.	33	1
34	2026-02-22 03:56:55.907566+00	Aset ditambahkan massal via Import Excel.	34	1
35	2026-02-22 03:56:55.909768+00	Aset ditambahkan massal via Import Excel.	35	1
36	2026-02-22 03:56:55.91264+00	Aset ditambahkan massal via Import Excel.	36	1
37	2026-02-22 03:56:55.914857+00	Aset ditambahkan massal via Import Excel.	37	1
38	2026-02-22 03:56:55.917089+00	Aset ditambahkan massal via Import Excel.	38	1
39	2026-02-22 03:56:55.919283+00	Aset ditambahkan massal via Import Excel.	39	1
40	2026-02-22 03:56:55.921505+00	Aset ditambahkan massal via Import Excel.	40	1
41	2026-02-22 03:56:55.923719+00	Aset ditambahkan massal via Import Excel.	41	1
42	2026-02-22 03:56:55.925924+00	Aset ditambahkan massal via Import Excel.	42	1
43	2026-02-22 03:56:55.928191+00	Aset ditambahkan massal via Import Excel.	43	1
44	2026-02-22 03:56:55.930432+00	Aset ditambahkan massal via Import Excel.	44	1
45	2026-02-22 03:56:55.932723+00	Aset ditambahkan massal via Import Excel.	45	1
46	2026-02-22 03:56:55.935137+00	Aset ditambahkan massal via Import Excel.	46	1
47	2026-02-22 03:56:55.937599+00	Aset ditambahkan massal via Import Excel.	47	1
48	2026-02-22 03:57:35.731883+00	Harga berubah dari '0' menjadi '5000000'.	46	1
49	2026-02-22 03:58:01.895873+00	Pengguna Sebelumnya berubah dari '-' menjadi 'Thomas Ali Sanjaya'; Divisi Sebelumnya berubah dari '-' menjadi 'Purchasing'; Pengguna Saat Ini berubah dari 'Thomas Ali Sanjaya' menjadi 'Jonathan'; Dept/Divisi Saat Ini berubah dari 'Purchasing' menjadi 'trade'.	7	1
\.


--
-- Data for Name: assets_kategori; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.assets_kategori (id, nama) FROM stdin;
1	Laptop
2	Handphone
3	Tablet
4	Printer
\.


--
-- Data for Name: assets_lokasi; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.assets_lokasi (id, nama) FROM stdin;
1	Gedung 32
2	Sumatera
3	Gedung 39
4	Jabodetabek
5	Gedung 38
6	Forest House
7	Gedung 34
8	Jawa
9	Gudang Karanggan 2 (Cabang Bogor)
10	Kalimantan
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add asset	7	add_asset
26	Can change asset	7	change_asset
27	Can delete asset	7	delete_asset
28	Can view asset	7	view_asset
29	Can add kategori	9	add_kategori
30	Can change kategori	9	change_kategori
31	Can delete kategori	9	delete_kategori
32	Can view kategori	9	view_kategori
33	Can add lokasi	10	add_lokasi
34	Can change lokasi	10	change_lokasi
35	Can delete lokasi	10	delete_lokasi
36	Can view lokasi	10	view_lokasi
37	Can add asset history	8	add_assethistory
38	Can change asset history	8	change_assethistory
39	Can delete asset history	8	delete_assethistory
40	Can view asset history	8	view_assethistory
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$xRqnczRndOfXMc0rsaZoW2$/7gOXjfqdOnxjeg6+Ii2euXIRaSot5eQ/p7k+7OeY3o=	2026-02-22 03:56:34.792418+00	t	admin				t	t	2026-02-04 10:01:45.305009+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	assets	asset
8	assets	assethistory
9	assets	kategori
10	assets	lokasi
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-04 09:59:23.045041+00
2	auth	0001_initial	2026-02-04 09:59:23.111888+00
3	admin	0001_initial	2026-02-04 09:59:23.134296+00
4	admin	0002_logentry_remove_auto_add	2026-02-04 09:59:23.146503+00
5	admin	0003_logentry_add_action_flag_choices	2026-02-04 09:59:23.187507+00
6	assets	0001_initial	2026-02-04 09:59:23.266971+00
7	contenttypes	0002_remove_content_type_name	2026-02-04 09:59:23.29225+00
8	auth	0002_alter_permission_name_max_length	2026-02-04 09:59:23.308932+00
9	auth	0003_alter_user_email_max_length	2026-02-04 09:59:23.320959+00
10	auth	0004_alter_user_username_opts	2026-02-04 09:59:23.331658+00
11	auth	0005_alter_user_last_login_null	2026-02-04 09:59:23.343239+00
12	auth	0006_require_contenttypes_0002	2026-02-04 09:59:23.345326+00
13	auth	0007_alter_validators_add_error_messages	2026-02-04 09:59:23.355966+00
14	auth	0008_alter_user_username_max_length	2026-02-04 09:59:23.371166+00
15	auth	0009_alter_user_last_name_max_length	2026-02-04 09:59:23.382976+00
16	auth	0010_alter_group_name_max_length	2026-02-04 09:59:23.401445+00
17	auth	0011_update_proxy_permissions	2026-02-04 09:59:23.423224+00
18	auth	0012_alter_user_first_name_max_length	2026-02-04 09:59:23.435255+00
19	sessions	0001_initial	2026-02-04 09:59:23.447288+00
20	assets	0002_alter_asset_serial_number	2026-02-20 06:39:42.844753+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: mahsaserver
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
8szr2h2cueqmzvtqysp6gow3lfux2kr8	.eJxVjD0OwyAUg-_CXCH-CR275wzo8YCStgIpJFPVu5dIGdrFsvzZfhMP-1b83tPql0iuhJPLbxYAn6keID6g3hvFVrd1CfSo0JN2OreYXrez-3dQoJexBmMNQ8WEUxLADRMdF9KCAs1xyllyZpGJEWgjh8jsgKWks3BhQkE-X7XLNv4:1vnZi5:h3qQs93XpV6wuzYEoNKHGI7HwfSCK7kIiuM-KWTeCQc	2026-02-18 10:02:09.365871+00
lwpkxhn2y5q278eyzyjrpshyb05o7ki3	.eJxVjD0OwyAUg-_CXCH-CR275wzo8YCStgIpJFPVu5dIGdrFsvzZfhMP-1b83tPql0iuhJPLbxYAn6keID6g3hvFVrd1CfSo0JN2OreYXrez-3dQoJexBmMNQ8WEUxLADRMdF9KCAs1xyllyZpGJEWgjh8jsgKWks3BhQkE-X7XLNv4:1vna3j:1BBzXfFoc1UTwG75uRlq3nrhzm3hYNzEjKwfHD-Zy-0	2026-02-18 10:24:31.689631+00
rmgfgcddjaxsuygi2a6uqtkdw36voez4	.eJxVjD0OwyAUg-_CXCH-CR275wzo8YCStgIpJFPVu5dIGdrFsvzZfhMP-1b83tPql0iuhJPLbxYAn6keID6g3hvFVrd1CfSo0JN2OreYXrez-3dQoJexBmMNQ8WEUxLADRMdF9KCAs1xyllyZpGJEWgjh8jsgKWks3BhQkE-X7XLNv4:1vtizD:RfwqqJwjCmHVUhqmyA9ZJ44YUU01_FLARFUPcNJGUpA	2026-03-07 09:09:15.566218+00
koh3k909boklvt0hu8p47bstv19b1z47	.eJxVjD0OwyAUg-_CXCH-CR275wzo8YCStgIpJFPVu5dIGdrFsvzZfhMP-1b83tPql0iuhJPLbxYAn6keID6g3hvFVrd1CfSo0JN2OreYXrez-3dQoJexBmMNQ8WEUxLADRMdF9KCAs1xyllyZpGJEWgjh8jsgKWks3BhQkE-X7XLNv4:1vtj0o:jjn4vrryoQVWVSC6cgYjx2NOiA1BErAp2ZbBv7iuU64	2026-03-07 09:10:54.85954+00
\.


--
-- Name: assets_asset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.assets_asset_id_seq', 48, true);


--
-- Name: assets_assethistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.assets_assethistory_id_seq', 51, true);


--
-- Name: assets_kategori_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.assets_kategori_id_seq', 5, true);


--
-- Name: assets_lokasi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.assets_lokasi_id_seq', 11, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: mahsaserver
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: assets_asset assets_asset_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_asset
    ADD CONSTRAINT assets_asset_pkey PRIMARY KEY (id);


--
-- Name: assets_assethistory assets_assethistory_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_assethistory
    ADD CONSTRAINT assets_assethistory_pkey PRIMARY KEY (id);


--
-- Name: assets_kategori assets_kategori_nama_key; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_kategori
    ADD CONSTRAINT assets_kategori_nama_key UNIQUE (nama);


--
-- Name: assets_kategori assets_kategori_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_kategori
    ADD CONSTRAINT assets_kategori_pkey PRIMARY KEY (id);


--
-- Name: assets_lokasi assets_lokasi_nama_key; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_lokasi
    ADD CONSTRAINT assets_lokasi_nama_key UNIQUE (nama);


--
-- Name: assets_lokasi assets_lokasi_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_lokasi
    ADD CONSTRAINT assets_lokasi_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: assets_asset_kategori_id_9b4c973a; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX assets_asset_kategori_id_9b4c973a ON public.assets_asset USING btree (kategori_id);


--
-- Name: assets_asset_lokasi_id_9caf77be; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX assets_asset_lokasi_id_9caf77be ON public.assets_asset USING btree (lokasi_id);


--
-- Name: assets_assethistory_asset_id_83c6c599; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX assets_assethistory_asset_id_83c6c599 ON public.assets_assethistory USING btree (asset_id);


--
-- Name: assets_assethistory_changed_by_id_ff9fd028; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX assets_assethistory_changed_by_id_ff9fd028 ON public.assets_assethistory USING btree (changed_by_id);


--
-- Name: assets_kategori_nama_a88dfec7_like; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX assets_kategori_nama_a88dfec7_like ON public.assets_kategori USING btree (nama varchar_pattern_ops);


--
-- Name: assets_lokasi_nama_c5c3b15c_like; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX assets_lokasi_nama_c5c3b15c_like ON public.assets_lokasi USING btree (nama varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: mahsaserver
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: assets_asset assets_asset_kategori_id_9b4c973a_fk_assets_kategori_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_asset
    ADD CONSTRAINT assets_asset_kategori_id_9b4c973a_fk_assets_kategori_id FOREIGN KEY (kategori_id) REFERENCES public.assets_kategori(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assets_asset assets_asset_lokasi_id_9caf77be_fk_assets_lokasi_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_asset
    ADD CONSTRAINT assets_asset_lokasi_id_9caf77be_fk_assets_lokasi_id FOREIGN KEY (lokasi_id) REFERENCES public.assets_lokasi(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assets_assethistory assets_assethistory_asset_id_83c6c599_fk_assets_asset_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_assethistory
    ADD CONSTRAINT assets_assethistory_asset_id_83c6c599_fk_assets_asset_id FOREIGN KEY (asset_id) REFERENCES public.assets_asset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: assets_assethistory assets_assethistory_changed_by_id_ff9fd028_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.assets_assethistory
    ADD CONSTRAINT assets_assethistory_changed_by_id_ff9fd028_fk_auth_user_id FOREIGN KEY (changed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mahsaserver
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict wcJDNB8ZJZKWOAmm88HkSxtchOuYfgIdYpoVrZ1PXBmbxyiWlBnCmGxNsKE3K47

