# Generated by Django 6.0 on 2025-12-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Aset')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor Seri')),
                ('purchase_date', models.DateField(verbose_name='Tanggal Beli')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Harga')),
                ('status', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIPAKAI', 'Sedang Dipakai'), ('RUSAK', 'Rusak'), ('HILANG', 'Hilang')], default='TERSEDIA', max_length=20)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
