# Generated by Django 6.0 on 2026-01-09 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Aset')),
                ('barcode_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Barcode')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor Seri')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Beli')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Harga')),
                ('status', models.CharField(choices=[('TERSEDIA', 'Tersedia'), ('DIPAKAI', 'Sedang Dipakai'), ('RUSAK', 'Rusak'), ('HILANG', 'Hilang')], default='TERSEDIA', max_length=20)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('current_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pengguna Saat Ini')),
                ('current_dept', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dept/Divisi Saat Ini')),
                ('prev_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pengguna Sebelumnya')),
                ('prev_dept', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dept/Divisi Sebelumnya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Lokasi',
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.kategori'),
        ),
        migrations.AddField(
            model_name='asset',
            name='lokasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.lokasi'),
        ),
    ]
