# Generated by Django 6.0 on 2025-12-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='barcode_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Barcode'),
        ),
    ]
