# Generated by Django 6.0 on 2025-12-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_dept',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dept/Divisi Saat Ini'),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pengguna Saat Ini'),
        ),
        migrations.AddField(
            model_name='asset',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='lokasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='prev_dept',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dept/Divisi Sebelumnya'),
        ),
        migrations.AddField(
            model_name='asset',
            name='prev_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pengguna Sebelumnya'),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
