# Generated by Django 6.0 on 2025-12-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_current_dept_asset_current_user_asset_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kategori',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('PC', 'PC'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Server', 'Server'), ('Network', 'Network'), ('UPS', 'UPS'), ('Handphone', 'Handphone'), ('Tablet', 'Tablet'), ('Webcam', 'Webcam'), ('Speaker', 'Speaker')], default='PC', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='lokasi',
            field=models.CharField(choices=[('Gedung 32', 'Gedung 32'), ('Gedung 34', 'Gedung 34'), ('Gedung 38', 'Gedung 38'), ('Gedung 39', 'Gedung 39')], default='Gedung 32', max_length=50),
            preserve_default=False,
        ),
    ]
