# Generated by Django 6.0 on 2026-01-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='Harga'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Beli'),
        ),
    ]
